#!/usr/bin/with-contenv bash

CACHE_DIR="/share/onnxasr"
export HOME="${CACHE_DIR}"
mkdir -p "${CACHE_DIR}"

export PYTHONPATH=/app:$PYTHONPATH

bashio::log.info "Starting ONNX ASR server..."

MODEL=$(bashio::config 'model')
QUANTIZATION=$(bashio::config 'quantization')
DEVICE=$(bashio::config 'device')
PORT=$(bashio::config 'port')

ARGS=(
    --model "${MODEL}"
    --uri "tcp://0.0.0.0:${PORT}"
    --quantization "${QUANTIZATION}"
    --device "${DEVICE}"
)

if bashio::config.true 'debug'; then
    ARGS+=(--debug)
    bashio::log.info "Running ONNX ASR in DEBUG mode."

    bashio::log.info "Model: ${MODEL}, Port: ${PORT}, Quantization: ${QUANTIZATION}, Device: ${DEVICE}"
else
    bashio::log.info "Running ONNX ASR."
    bashio::log.info "Model: ${MODEL}, Port: ${PORT}"
fi

exec python3 -m wyoming_onnxasr "${ARGS[@]}"

bashio::log.fatal "Failed to execute python server!"
